environment:

  matrix:
  
  - PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.9"
    PYTHON_ARCH: "32"

  - PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7.9"
    PYTHON_ARCH: "64"
    
  - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "32"

  - PYTHON: "C:\\Python35-x64"
    PYTHON_VERSION: "3.5.0"
    PYTHON_ARCH: "64"  
  
install:

  # Install Python (from the official .msi of http://python.org) and pip when not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be done from inside the
  # powershell script as it would require to restart the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  
  # Upgrade to the latest version of pip to avoid it displaying warnings about it being out of date.
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "%CMD_IN_ENV% pip install numpy scipy nose"
  
build_script:
  # Build the compiled extension
  - "%CMD_IN_ENV% python setup.py build"

test_script:
  # Run the project tests
  - "%CMD_IN_ENV% python setup.py nosetests"
