install:
  - ps: curl https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
  - Miniconda3-latest-Windows-x86_64.exe

build_script:
  - "python setup.py build"

test_script:
  - "python setup.py nosetests"
